
spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  jwt:
    key: CODESTARTES_STQREWR_EWREWR_EXTENDKEY  # 민감한 정보는 시스템 환경 변수에서 로드한다.
    access-token-expiration-minutes: 1
    refresh-token-expiration-minutes: 420
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moneymade-db.c3r6azftukjh.ap-northeast-2.rds.amazonaws.com:3306/moneymade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 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  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420

chatgpt:
  api-key:

google:
  recaptcha:
    secret-key: 6LfdeKEmAAAAAE6DVb7hyb-hTiVTpGkNHv-pnd4k